### ISSUE TITLE
ポイント集計、ランキング表示機能

### ISSUE THREAD

**Issue by mdb-konno** [MeHerBu/Quiz#4]

**Comment by mdb-konno** [comment]
＞大島さん
森田さんに引き継ぎメッセージをお願いいたしますー

**Comment by oshimayuka** [comment]
＞森田さん
何もやってないので一からよろしくお願いします！お元気でー！
![b8rbpgecyaetvet](https://cloud.githubusercontent.com/assets/6603249/6746380/88831b1e-cf0a-11e4-8097-c87c4c6f06eb.png)

**Comment by mdb-konno** [comment]
＞森田さん
難易度高いかもしれませんが、よろしくお願いいたします！

タイトルを「ポイント集計、ランキング表示機能」に変えました。

（実装イメージ）
ミルクココア側
・Aさん：5pt
・Bさん：10pt
・Cさん：3pt
という情報があり。

それをJavaScriptで取得して、ソートさせる
